version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run:
          name: download deps
          command: go mod download
      - run:
          name: run tests
          command: |
            mkdir -p test-results/
            gotestsum --junitfile test-results/junit.xml -- -race ./...
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results